name: JavaFx App Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and package Client module
        run: |
          mvn clean package
        working-directory: ./Client

      - name: Calculate SHA256 hash for Client module
        run: |
          cd ./Client/target
          sha256sum client-1.0-shaded.jar > ../../E-voting.txt
        working-directory: .

      - name: Deploy Client module artifact
        uses: actions/upload-artifact@v3
        with:
          name: E-Voting
          path: ./Client/target/client-1.0-shaded.jar

      - name: Deploy Client module SHA256 hash
        uses: actions/upload-artifact@v3
        with:
          name: E-Voting-SHA256
          path: ./E-voting-SHA256.txt

  build-and-deploy-ballot-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and package BallotGenerator module
        run: |
          mvn clean package
        working-directory: ./BallotGenerator

      - name: Calculate SHA256 hash for BallotGenerator module
        run: |
          cd ./BallotGenerator/target
          sha256sum BallotGenerator-1.0-shaded.jar > ../../BallotGenerator.txt
        working-directory: .

      - name: Deploy BallotGenerator module artifact
        uses: actions/upload-artifact@v3
        with:
          name: BallotGenerator
          path: ./BallotGenerator/target/BallotGenerator-1.0-shaded.jar

      - name: Deploy BallotGenerator module SHA256 hash
        uses: actions/upload-artifact@v3
        with:
          name: BallotGenerator-SHA256
          path: ./BallotGenerator.txt

  build-and-deploy-vote-counter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and package VoteCounter module
        run: |
          mvn clean package
        working-directory: ./VoteCounter

      - name: Calculate SHA256 hash for VoteCounter module
        run: |
          cd ./VoteCounter/target
          sha256sum VoteCounter-1.0-shaded.jar > ../../VoteCounter.txt
        working-directory: .

      - name: Deploy VoteCounter module artifact
        uses: actions/upload-artifact@v3
        with:
          name: VoteCounter
          path: ./VoteCounter/target/VoteCounter-1.0-shaded.jar

      - name: Deploy VoteCounter module SHA256 hash
        uses: actions/upload-artifact@v3
        with:
          name: VoteCounter-SHA256
          path: ./VoteCounter.txt


  build-and-deploy-password-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and package PasswordGenerator module
        run: |
          mvn clean package
        working-directory: ./PasswordGenerator

      - name: Calculate SHA256 hash for PasswordGenerator module
        run: |
          cd ./PasswordGenerator/target
          sha256sum PasswordGenerator-1.0-shaded.jar > ../../PasswordGenerator.txt
        working-directory: .

      - name: Deploy PasswordGenerator module artifact
        uses: actions/upload-artifact@v3
        with:
          name: PasswordGenerator
          path: ./PasswordGenerator/target/PasswordGenerator-1.0-shaded.jar

      - name: Deploy PasswordGenerator module SHA256 hash
        uses: actions/upload-artifact@v3
        with:
          name: PasswordGenerator-SHA256
          path: ./PasswordGenerator.txt
