name: JavaFx App Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and package Client module
        run: |
          mvn clean package
        working-directory: ./Client

      - name: Rename Client module artifact
        run: |
          cd ./Client/target
          mv Client-1.0-shaded.jar E-voting.jar
        working-directory: .

      - name: Calculate SHA256 hash for Client module
        run: |
          cd ./Client/target
          sha256sum E-voting.jar > ../../E-voting-SHA256.txt
        working-directory: .

      - name: Deploy Client module artifact
        uses: actions/upload-artifact@v3
        with:
          name: E-Voting
          path: ./Client/target/E-voting.jar
          content-type: 'application/java-archive'

      - name: Deploy Client module SHA256 hash
        uses: actions/upload-artifact@v3
        with:
          name: E-Voting-SHA256
          path: ./E-voting-SHA256.txt
          content-type: 'text/plain'

  build-and-deploy-ballot-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and package BallotGenerator module
        run: |
          mvn clean package
        working-directory: ./BallotGenerator

      - name: Rename BallotGenerator module artifact
        run: |
          cd ./BallotGenerator/target
          mv BallotGenerator-1.0-shaded.jar BallotGenerator.jar
        working-directory: .

      - name: Calculate SHA256 hash for BallotGenerator module
        run: |
          cd ./BallotGenerator/target
          sha256sum BallotGenerator.jar > ../../BallotGenerator-SHA256.txt
        working-directory: .

      - name: Deploy BallotGenerator module artifact
        uses: actions/upload-artifact@v3
        with:
          name: BallotGenerator
          path: ./BallotGenerator/target/BallotGenerator.jar
          content-type: 'application/java-archive'

      - name: Deploy BallotGenerator module SHA256 hash
        uses: actions/upload-artifact@v3
        with:
          name: BallotGenerator-SHA256
          path: ./BallotGenerator-SHA256.txt
          content-type: 'text/plain'

  build-and-deploy-vote-counter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and package VoteCounter module
        run: |
          mvn clean package
        working-directory: ./VoteCounter

      - name: Rename VoteCounter module artifact
        run: |
          cd ./VoteCounter/target
          mv VoteCounter-1.0-shaded.jar VoteCounter.jar
        working-directory: .

      - name: Calculate SHA256 hash for VoteCounter module
        run: |
          cd ./VoteCounter/target
          sha256sum VoteCounter.jar > ../../VoteCounter-SHA256.txt
        working-directory: .

      - name: Deploy VoteCounter module artifact
        uses: actions/upload-artifact@v3
        with:
          name: VoteCounter
          path: ./VoteCounter/target/VoteCounter.jar
          content-type: 'application/java-archive'

      - name: Deploy VoteCounter module SHA256 hash
        uses: actions/upload-artifact@v3
        with:
          name: VoteCounter-SHA256
          path: ./VoteCounter-SHA256.txt
          content-type: 'text/plain'


  build-and-deploy-password-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and package PasswordGenerator module
        run: |
          mvn clean package
        working-directory: ./PasswordGenerator

      - name: Rename PasswordGenerator module artifact
        run: |
          cd ./PasswordGenerator/target
          mv PasswordGenerator-1.0-shaded.jar PasswordGenerator.jar
        working-directory: .

      - name: Calculate SHA256 hash for PasswordGenerator module
        run: |
          cd ./PasswordGenerator/target
          sha256sum PasswordGenerator.jar > ../../PasswordGenerator-SHA256.txt
        working-directory: .

      - name: Deploy PasswordGenerator module artifact
        uses: actions/upload-artifact@v3
        with:
          name: PasswordGenerator
          path: ./PasswordGenerator/target/PasswordGenerator.jar
          content-type: 'application/java-archive'

      - name: Deploy PasswordGenerator module SHA256 hash
        uses: actions/upload-artifact@v3
        with:
          name: PasswordGenerator-SHA256
          path: ./PasswordGenerator-SHA256.txt
          content-type: 'text/plain'
